# PostgreSQL.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER_DEV'] %>
  password: <%= ENV['DB_PASSWORD_DEV'] %>

development:
  <<: *default
  database: todo_api_pst_development

test:
  <<: *default
  database: todo_api_pst_test

production:
  <<: *default
  database: todo_api_pst_production
  username: <%= ENV['DB_USER_PRD'] %>
  password: <%= ENV['DB_PASSWORD_PRD'] %>
